#!/bin/sh

source /home/$(whoami)/.syncaurrc

ARCH=$(uname -m)

echo -e "\e[44;31m==> \e[1;37mНачинаем синхронизацию...\e[0m"
fetch --sync
fetch --trunksync
echo -en "\e[44;31m==> \e[1;37mХотите ли Вы начать сборку? (y/n) \e[0m"
read a
if [[ $a == "y" ]]; then
	builder;
	builder --trunk;
fi
cd $TEMPDIR;
echo -e "\e[1;31m==> \e[1;37mОтправка собранных пакетов в $FTP.\e[0m";
	    lftp $FTP/$ARCH -u $USER,$PASS -e "mput *.pkg.tar.xz; exit";
echo -en "\e[44;31m==> \e[1;37mХотите ли Вы удалить собранные пакеты из временной директории? (y/n) \e[0m"
read a
if [[ $a == "y" ]]; then
	    rm *.pkg.tar.xz;
fi
