#!/bin/sh

echo -e "\e[44;31m==> \e[1;37mНачинаем синхронизацию...\e[0m"
fetch --sync
fetch --trunksync
echo -en "\e[44;31m==> \e[1;37mХотите ли Вы начать сборку? (y/n) \e[0m"
read a
if [[ $a == "y" ]]; then
	builder;
	builder --trunk;
fi
