#!/bin/sh

source /home/$(whoami)/.syncaurrc

ARCH=$(uname -m)

if [[ $1 == "trunk" ]]; then
	cd $TRUNKDIR;
else
	cd $PKGDIR;
fi

for DIR in $(ls);
    do if [[ -d $DIR ]]; then
	PKGLIST=$PKGLIST" $(ls $DIR/*.pkg.tar.xz)";
    fi
done

echo $PKGLIST

lftp repo.mind-x.org/$ARCH -u $USER,$PASS -e "mput $PKGLIST; exit"
